// SPDX-License-Identifier: MIT
pragma solidity 0.8.37;

import {Test} from "forge-std/Test.sol";
import {BlsOutcome} from "./BlsOutcome.sol";

/// @dev Loads the committed BLS fixtures under test/fixtures/bls/ (generated by tooling/src/gen-bls-fixtures.ts,
///      ADR-0001: forge only reads JSON, `fs_permissions` grants ./test/fixtures). Struct field names match the JSON
///      keys; forge coerces by the type description, so order is free. The harness and the outcome vocabulary come
///      from BlsOutcome.
abstract contract BlsFixtures is Test, BlsOutcome {
    string internal constant FIXTURES = "test/fixtures/bls/";

    struct XmdVector {
        bytes dst;
        bytes dstReduced;
        uint256 lenInBytes;
        bytes msg;
        bytes uniformBytes;
    }

    struct H2cVector {
        bytes dst;
        bytes msg;
        bytes px;
        bytes py;
    }

    struct EipPositive {
        string name;
        uint256 precompile;
        bytes input;
        bytes expected;
    }

    struct EipFail {
        string name;
        uint256 precompile;
        bytes input;
        string expectedError;
    }

    struct Round {
        bool nobleAccepts;
        bytes32 randomness;
        uint256 round;
        bytes signature;
    }

    struct Negative {
        string name;
        string category;
        string encoding;
        bytes point;
        uint256 round;
        string dst;
        bool nobleAccepts;
        string nobleReason;
        string solidity;
        string g1add;
    }

    struct Control {
        string encoding;
        bytes point;
        uint256 round;
        string dst;
        bool nobleAccepts;
    }

    // ---- loaders ----

    function loadXmd() internal view returns (XmdVector[] memory) {
        return abi.decode(
            vm.parseJsonTypeArray(
                vm.readFile(string.concat(FIXTURES, "rfc9380-expand-message-xmd.json")),
                ".vectors",
                "XmdVector(bytes dst,bytes dstReduced,uint256 lenInBytes,bytes msg,bytes uniformBytes)"
            ),
            (XmdVector[])
        );
    }

    function loadH2c() internal view returns (H2cVector[] memory) {
        return abi.decode(
            vm.parseJsonTypeArray(
                vm.readFile(string.concat(FIXTURES, "rfc9380-hash-to-curve-g1.json")),
                ".vectors",
                "H2cVector(bytes dst,bytes msg,bytes px,bytes py)"
            ),
            (H2cVector[])
        );
    }

    function loadEip2537() internal view returns (EipPositive[] memory positive, EipFail[] memory fail) {
        string memory json = vm.readFile(string.concat(FIXTURES, "eip2537.json"));
        positive = abi.decode(
            vm.parseJsonTypeArray(
                json, ".vectors.positive", "EipPositive(string name,uint256 precompile,bytes input,bytes expected)"
            ),
            (EipPositive[])
        );
        fail = abi.decode(
            vm.parseJsonTypeArray(
                json, ".vectors.fail", "EipFail(string name,uint256 precompile,bytes input,string expectedError)"
            ),
            (EipFail[])
        );
    }

    function loadRounds() internal view returns (Round[] memory) {
        return abi.decode(
            vm.parseJsonTypeArray(
                vm.readFile(string.concat(FIXTURES, "quicknet-rounds.json")),
                ".rounds",
                "Round(bool nobleAccepts,bytes32 randomness,uint256 round,bytes signature)"
            ),
            (Round[])
        );
    }

    function loadNegatives() internal view returns (Negative[] memory cases, Control memory control) {
        string memory json = vm.readFile(string.concat(FIXTURES, "quicknet-negatives.json"));
        cases = abi.decode(
            vm.parseJsonTypeArray(
                json,
                ".cases",
                "Negative(string name,string category,string encoding,bytes point,uint256 round,string dst,"
                "bool nobleAccepts,string nobleReason,string solidity,string g1add)"
            ),
            (Negative[])
        );
        control = abi.decode(
            vm.parseJsonType(
                json, ".control", "Control(string encoding,bytes point,uint256 round,string dst,bool nobleAccepts)"
            ),
            (Control)
        );
    }
}
