#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

# gh cannot resolve the git@github-nutz SSH alias in origin; name the repo for it.
export GH_REPO="${GH_REPO:-nutzwtf/nutz-contracts}"
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
PINNED_BLOCK=62393542   # FORK_BLOCK in test/fork/ConverterFork.t.sol
WETH=0x0Bd7D308f8E1639FAb988df18A8011f41EAcAD73

banner "Chainstack archive node for Robinhood Chain (4663)"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Chainstack account"
say "Chainstack runs Robinhood Chain mainnet in archive mode; docs/setup/environment.md §5.1 names it as the primary RPC."
open_url "https://console.chainstack.com/user/account/create"
step "Sign up (email or GitHub/Google), confirm the address, and land in the console."
note "If you already have an account, sign in instead: https://console.chainstack.com"
pause "Signed in to the console? Press Enter."

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Plan: archive data needs a paid plan"
say "Archive nodes (all historical state) require a paid plan on a Global Node. The free Developer plan has no archive data,"
say "and a full node only keeps the latest 128 blocks, so the pinned-block fork test would fail on it."
say "Growth (\$49/month, 20M request units, archive included) is the smallest plan that works."
note "Billing: 1 RU per request on a full node, 2 RU per request on an archive node. One fork run is a few thousand requests."
open_url "https://console.chainstack.com/user/settings/billing"
step "Choose the Growth plan (or higher) and add a payment method."
pause "Plan active? Press Enter."

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Deploy the node"
open_url "https://console.chainstack.com/nodes"
step "Click the button to add / deploy a node."
step "Protocol: Robinhood Chain.  Network: Mainnet (chain id 4663)."
step "Type: Global Node.  Mode: Archive.  (Region: whatever is offered; Global Nodes are multi-region.)"
step "Name it something like nutz-4663-archive and deploy."
warn "Mode must be Archive. A Full node answers today's blocks and fails on every historical read."
pause "Node status shows Running? Press Enter."

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Endpoints into .env"
step "Open the node, then its 'Access and credentials' section."
step "Copy the HTTPS endpoint (https://…chainstack.com/<key>) and the WSS endpoint (wss://…)."
note "The key is part of the URL: both values are secrets. They go into the gitignored .env only; gitleaks blocks a paste anywhere else."
ask_secret RPC_4663 "Paste the HTTPS endpoint:"
ask_secret RPC_4663_WS "Paste the WSS endpoint:"
if [[ "$RPC_4663" != https://* ]]; then warn "that does not look like an https:// URL"; fi
if [[ "$RPC_4663_WS" != wss://* ]]; then warn "that does not look like a wss:// URL"; fi
write_env RPC_4663 "$RPC_4663"
write_env RPC_4663_WS "$RPC_4663_WS"
export RPC_4663 RPC_4663_WS

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Verify the endpoint with cast"
if ! command -v cast >/dev/null 2>&1; then
  warn "cast not on PATH (mise not activated?). Run 'mise install' and re-run this wizard from the repo."
  SKIPPED+=("endpoint verification: cast not found")
else
  chain_id=$(cast chain-id --rpc-url "$RPC_4663" 2>&1 | tail -n1 || true)
  if [[ "$chain_id" == "4663" ]]; then say "${GREEN}✓${RESET} chain id 4663"; else warn "chain id came back as '$chain_id', expected 4663"; fi
  latest=$(cast block-number --rpc-url "$RPC_4663" 2>/dev/null || echo 0)
  say "latest block: $latest"
  old=$(( latest > 1000000 ? latest - 1000000 : 1 ))
  if cast balance "$WETH" --block "$old" --rpc-url "$RPC_4663" >/dev/null 2>&1; then
    say "${GREEN}✓${RESET} archive: balance at block $old answered"
  else
    warn "block $old is not served: this is NOT an archive node. Check the node's Mode in the console."
    SKIPPED+=("archive check failed: redeploy the node in Archive mode")
  fi
  if cast balance "$WETH" --block "$PINNED_BLOCK" --rpc-url "$RPC_4663" >/dev/null 2>&1; then
    say "${GREEN}✓${RESET} pinned FORK_BLOCK $PINNED_BLOCK is served"
  else
    warn "pinned FORK_BLOCK $PINNED_BLOCK not served (archive still syncing?). Try again later."
  fi
  ws_block=$(cast block-number --rpc-url "$RPC_4663_WS" 2>/dev/null || echo "")
  if [[ -n "$ws_block" ]]; then say "${GREEN}✓${RESET} WebSocket answers (block $ws_block)"; else warn "WebSocket endpoint did not answer; the indexer will need it later, not this repo"; fi
fi
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "GitHub Actions secret RPC_4663"
say "The CI 'fork' job (manual dispatch + nightly) reads the repository secret RPC_4663 and skips when it is empty."
set_secret RPC_4663 "$RPC_4663"
if [[ " ${WRITTEN_SECRET[*]:-} " != *" RPC_4663 "* ]]; then
  say "gh could not set it (its GITHUB_TOKEN does not authenticate on this machine), so add it in the browser:"
  open_url "https://github.com/nutzwtf/nutz-contracts/settings/secrets/actions"
  step "New repository secret → Name: RPC_4663 → Secret: the HTTPS endpoint → Add secret."
  pause "Secret added? Press Enter."
fi
say "Keep an off-machine copy of both URLs (1Password vault, per docs/setup/environment.md §5.1) so a lost laptop is not a lost node."
pause

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Run the fork test at the pinned block"
say "forge test --match-path test/fork/ConverterFork.t.sol --fork-url robinhood -vvv"
note "About six tests, each forking block $PINNED_BLOCK; a minute or two, a few thousand archive requests."
if confirm "Run it now?"; then
  if command -v forge >/dev/null 2>&1; then
    forge test --match-path test/fork/ConverterFork.t.sol --fork-url "$RPC_4663" -vvv || warn "fork tests failed; see the output above"
  else
    warn "forge not on PATH; run the command above from an activated shell"
  fi
fi
say "To run the CI job: GitHub → Actions → ci → Run workflow (the fork job only runs on dispatch or nightly)."
pause

finish
